# Generated by Django 3.2.7 on 2022-01-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_details_contact_person_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('call denied', 'call denied'), ('interested', 'interested'), ('not interested', 'not interested'), ('wrong number', 'wrong number'), ('follow up', 'follow up'), ('dead', 'dead')], default='call denied', max_length=50)),
                ('next_follow_up_date', models.DateField()),
                ('remark', models.CharField(max_length=1000)),
                ('last_call_date', models.DateField()),
            ],
        ),
    ]
