# Generated by Django 3.2.7 on 2022-01-10 06:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_contact_company_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='company_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company_details'),
            preserve_default=False,
        ),
    ]
