# Generated by Django 3.2.7 on 2022-01-10 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_contact_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company_details'),
        ),
    ]
