# Generated by Django 3.2.7 on 2022-01-12 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_contact_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='company_id',
            new_name='company_ID',
        ),
    ]
